feat: display more task runs on the page
influxdata/ui pull request #1102
Opened 2021-04-02 23:15 UTC by russorat

We fetch 100 task runs from the API, then only show 20 of them for some reason. this updates to show all 100 task runs if they are available.

2021-04-02 23:23 UTC, drdelambre requested changes
Just remove the slice all together. No need for the const or nothing

2021-04-02 23:23 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 38 | :red_circle:
accessibility | 96 | :green_circle:
best-practices | 93 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1102)

2021-04-05 12:17 UTC, Asalem1 approved these changes
Here’s to breaking prod

2021-04-05 16:14 UTC, russorat commented
🤦🏼  thanks! updated

2021-04-05 17:21 UTC, drdelambre approved these changes

2021-04-05 17:22 UTC, merged