chore: make dashboards filter term persist across pages
influxdata/ui pull request #1160
Opened 2021-04-09 17:02 UTC by subirjolly

Closes #844 

**Before**
![before](https://user-images.githubusercontent.com/1637395/114215667-db815480-9933-11eb-9f63-fb2b48e5dc81.gif)

**After**
![after](https://user-images.githubusercontent.com/1637395/114215678-e0460880-9933-11eb-8922-068d18eb497e.gif)

2021-04-09 17:12 UTC, Asalem1 requested changes
Besides the comments, my concern with this approach is that we are now dispatching an event whenever we search through dashboards. This might cause us to rerender the DOM a bunch, which might cause a performance hit. Is there any chance we can get a performance chart to see the difference between this implementation and the original? I know the original isn't what we're striving for, but it might be possible for us to use that as a barometer for success here when measuring how performant this part of the app currently is vs how it fairs with the refactor

2021-04-09 17:12 UTC, Asalem1 commented on src/dashboards/components/dashboard_index/DashboardsIndex.tsx
> +                  onFilterChange={this.props.setSearchTerm}
if the `onSearch` and `onFilterChange` are being mapped to props, there's no reason for us to prop drill. We could just map it out directly to the child

2021-04-09 17:12 UTC, Asalem1 commented on src/dashboards/components/dashboard_index/DashboardsIndex.tsx
> +  const searchTerm = state.resources.dashboards['searchTerm']
nit: We can probably consolidate these to a `getAll`, then just get the individual properties:

https://github.com/influxdata/ui/blob/master/src/resources/selectors/index.ts#L14

So something like:

```
const {sortOptions, searchTerm} = getAll<Dashboard>(
    state,
    ResourceType.Dashoards
  )
```

2021-04-09 17:14 UTC, joelfried approved these changes

2021-04-09 17:14 UTC, joelfried commented on cypress/e2e/shared/dashboardsIndex.test.ts
> +        cy.wait(1000)
Can we handle the navigation without these hard coded wait here and below?  (And looking [here](https://docs.cypress.io/guides/references/best-practices#Unnecessary-Waiting) I'm not sure if both of these are necessary.  Perhaps you need to add a cy.get after the click on 501 before you go back though? Not sure on that.)

2021-04-09 17:23 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 91 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1160)

2021-04-09 19:12 UTC, Asalem1 commented on src/dashboards/reducers/dashboards.ts
> +        draftState['searchTerm'] = searchTerm
nit: for stylistic consistencies let's use dot notation

2021-04-10 13:39 UTC, Asalem1 approved these changes
Looks great. Happy to get this in first thing Monday  morning

2021-04-12 18:11 UTC, merged