feat: pause cell feature
influxdata/ui pull request #1240
Opened 2021-04-19 20:54 UTC by ShmuelLotman

Closes #

Please see the epic for Dashboard Auto Refresh for context about this feature. Introduces ability to pause cells, will be integrated with broader dashboard auto refresh work. 

### Feature flag
Under feature flag: `pauseCell`

2021-04-19 21:00 UTC, Asalem1 submitted a review, later dismissed
Looks good to me!

2021-04-19 21:12 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 58 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1240)

2021-04-21 17:47 UTC, drdelambre commented on src/shared/apis/queryCache.ts
> +const calculateHashedVariables = (allVars: Variable[], query: string) => {
this logic is defined elsewhere. merge the two concepts so that we dont have competing definitions of a variable hash as this code is maintained

2021-04-21 21:00 UTC, drdelambre approved these changes
thanks for putting those together

2021-04-22 17:44 UTC, drdelambre requested changes
i'm taking back my review until i get some ANSWERS
is the intent that we can pause any query in the system, or just cells?
what happens if i pause a query on the dashboard, then make the exact same query over on the notebooks?
it doesn't make a lot of sense to put it on the caching layer, where really we just want a cell, displayed in the dashboard, to not send a query when autorefresh is rolling.

2021-04-22 19:46 UTC, Asalem1 commented
Gonna pause on this until we get some product clarity here;

https://github.com/influxdata/ui/issues/1207#issuecomment-825067115

2021-05-05 19:57 UTC, closed without merging