feat: breaking out the examples
influxdata/ui pull request #1333
Opened 2021-04-30 20:44 UTC by subirjolly

Closes #

2021-05-04 13:12 UTC, Asalem1 commented
Is this a draft PR?

2021-05-05 18:50 UTC, subirjolly commented
> Is this a draft PR?

@drdelambre worked on it. I just rebased it and am trying to merge it to continue working on #576 
This PR has some base components/pre-reqs which are needed for the story. @drdelambre Feel free to elaborate or add.

2021-05-05 19:13 UTC, Asalem1 requested changes
This PR touched 118 files and has a lot of code deleted / modified. I'd love a PR description to give me a better idea of:

- What this PR does
- Why this PR is necessary
- What this PR affects
- Potentially an image / gif of this in action

2021-05-05 20:03 UTC, Asalem1 reviewed
Would love an image to validate that everything still works, maybe some e2e tests

2021-05-05 20:21 UTC, drdelambre commented on src/writeData/clients/Kotlin/index.ts
> +    featureFlag: 'client-library--kotlin',
@subirjolly was this one of your conflicts?

2021-05-05 20:22 UTC, drdelambre commented on src/shared/containers/index.tsx
> -export const TelegrafPluginsPage = lazy(() =>
yes

2021-05-05 20:23 UTC, Asalem1 commented on src/shared/containers/index.tsx
> -export const TelegrafPluginsPage = lazy(() =>
it looks like the imports were just moved from one part of the file to another.

2021-05-05 20:24 UTC, drdelambre commented
re feature flags: wut?
re line protocol: wut?

2021-05-05 20:25 UTC, subirjolly commented on src/writeData/clients/Kotlin/index.ts
> +    featureFlag: 'client-library--kotlin',
Don't think so. It was just the markdowns removal

2021-05-05 20:25 UTC, subirjolly commented
> This PR touched 118 files and has a lot of code deleted / modified. I'd love a PR description to give me a better idea of:
> 
> * What this PR does
> * Why this PR is necessary
> * What this PR affects
> * Potentially an image / gif of this in action

Absolutely. Just prepared a draft. Getting it taken a look by Boaty.

2021-05-05 20:27 UTC, Asalem1 commented
> re feature flags: wut?
> re line protocol: wut?

Each of the files has a unique feature flag associated with it. Is there a reason we don't wanna lump em under section-specific ones?

Re: line protocol, all the sections we're adding have a blurb about writing data with line protocol. Is the client library section about integrating a client library? Why are we giving the user an ability to write line protocol? Maybe I'm misunderstanding things a bit here

2021-05-05 21:06 UTC, subirjolly commented
> This PR touched 118 files and has a lot of code deleted / modified. I'd love a PR description to give me a better idea of:
> 
> * What this PR does
> * Why this PR is necessary
> * What this PR affects
> * Potentially an image / gif of this in action

done!

2021-05-05 21:09 UTC, subirjolly commented on src/writeData/clients/Kotlin/index.ts
> +    featureFlag: 'client-library--kotlin',
This file is not in master.

2021-05-05 21:22 UTC, drdelambre commented
re line protocol: i have no idea what is going on so lemme rewind
for all of the client libraries, we have one markdown file to teach the user how to use said library that has a description, information on initializing the library to talk to the server, 0-n ways on how to write to the db using the client, and an example of how to use the client library to execute a flux query.
this pr extracts those examples and puts them into `.example` files so that we can reuse them later on other pages
i have no opinion about whether or not we should provide the user with an example on how to use line protocol, just that if we provided it before decomposing the markdown file, we should still provide it after.

2021-05-05 21:27 UTC, drdelambre commented
re feature flags: the reason it switched perspective from section level to client library level is that by introducing the concept of reusing these examples, we're implicitly declaring the ability to create side effects external to the existing implementation / visualization of these libraries. if you want to turn off the swift client examples (for... example), you'd want to turn them off not only for this page, but for every other page that implements them (notebooks `export as swift` being an upcoming one).

2021-05-05 21:28 UTC, drdelambre commented on src/shared/containers/index.tsx
> -export const TelegrafPluginsPage = lazy(() =>
yes

2021-05-05 21:29 UTC, drdelambre commented on src/writeData/clients/Kotlin/index.ts
> +    featureFlag: 'client-library--kotlin',
https://github.com/influxdata/ui/blob/master/src/writeData/components/clientLibraries/Kotlin.md

2021-05-05 21:51 UTC, Asalem1 approved these changes

2021-05-05 22:24 UTC, subirjolly commented
I also clicked around in most of the application and everything seems to be normal.

2021-05-05 22:24 UTC, merged