fix: update description
influxdata/ui pull request #2069
Opened 2021-07-19 20:36 UTC by russorat

Closes #

Updates the influxdb site description.

2021-07-19 20:36 UTC, TCL735 approved these changes

2021-07-19 20:55 UTC, timhallinflux requested changes

2021-07-19 20:55 UTC, timhallinflux commented on assets/index.html
> +      content="InfluxDB<%= htmlWebpackPlugin.options.titleAdd %> is a time series platform, purpose-built by InfluxData for monitoring metrics and events, provides real-time visibility into stacks, s
storing? as opposed to monitoring?

2021-07-20 13:55 UTC, russorat commented on assets/index.html
> +      content="InfluxDB<%= htmlWebpackPlugin.options.titleAdd %> is a time series platform, purpose-built by InfluxData for monitoring metrics and events, provides real-time visibility into stacks, s
```suggestion
      content="InfluxDB<%= htmlWebpackPlugin.options.titleAdd %> is a time series platform, purpose-built by InfluxData for storing metrics and events, provides real-time visibility into stacks, sensors, and systems."
```

2021-07-20 21:09 UTC, merged