feat: changed navigation to edit task to view task runs
influxdata/ui pull request #2133
Opened 2021-07-26 17:27 UTC by mtian725

Closes #2128

After clicking the task name, user is navigated to the task runs page now instead of the edit task page. `View task runs` from gearbox list also replaced with `Edit run`, which opens up the edit window.

## Before
https://user-images.githubusercontent.com/39343323/127032271-8fcb2548-d332-4095-a0a9-16525e4f00fb.mov

## After
https://user-images.githubusercontent.com/39343323/127031583-baad9376-a500-42f7-8847-7240f0b99c39.mov

2021-07-26 17:39 UTC, russorat commented on src/tasks/components/TaskCard.tsx
> +            label="Edit Run"
Edit Run or Edit Task?

2021-07-26 17:40 UTC, mtian725 commented on src/tasks/components/TaskCard.tsx
> +            label="Edit Run"
Should be Edit Task

2021-07-26 17:58 UTC, russorat approved these changes
LGTM

2021-07-26 22:37 UTC, hoorayimhelping approved these changes

2021-07-26 22:37 UTC, hoorayimhelping commented on src/tasks/components/TaskCard.tsx
>        window.open(url, '_blank')
I think we want to do something like this:
```suggestion
      window.open(url, '_blank', 'noopener')
```

it's a security issue https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

2021-07-26 23:57 UTC, mtian725 commented
Need to modify tests because changing the navigation causes many tests to break.

2021-07-27 22:39 UTC, genehynson requested changes
We need to remove the cypress command chaining in the tests. That will cause race conditions

2021-07-27 22:39 UTC, genehynson commented on cypress/e2e/shared/explorer.test.ts
> +              })
please avoid chaining cypress commands like this, it will cause race conditions https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/

2021-07-27 22:39 UTC, genehynson commented on cypress/e2e/shared/tasks.test.ts
> +          })
same here, avoid chaining

2021-07-27 22:39 UTC, genehynson commented on cypress/e2e/shared/tasks.test.ts
> +            })
would be great to fix the chaining here too

2021-07-27 22:39 UTC, genehynson commented on cypress/e2e/shared/tasks.test.ts
>                      })
remove the chaining here too

2021-07-27 22:39 UTC, genehynson commented on cypress/e2e/shared/tasks.test.ts
> +                  // verify that the previously input data exists
and here

2021-07-27 23:18 UTC, genehynson commented
Let me know if you want to pair up on fixing these tests, I'm happy to help

2021-07-30 20:50 UTC, genehynson approved these changes
Looks great! thanks!

2021-07-30 21:20 UTC, merged