test: try to prevent race conditions in annotations e2e tests
influxdata/ui pull request #2159
Opened 2021-07-27 22:22 UTC by hoorayimhelping

2021-07-27 22:24 UTC, Palakp41 approved these changes

2021-07-27 22:31 UTC, genehynson requested changes
I think this will make it worse

2021-07-27 22:35 UTC, genehynson commented on cypress/e2e/util/annotationsSetup.ts
> +                .click()
chaining like this will certainly cause more race conditions

2021-07-28 00:37 UTC, genehynson approved these changes
Looks great, thanks!!

![](https://media.giphy.com/media/4KxeicCUTvhrW/giphy.gif)

2021-07-28 18:15 UTC, merged