fix: don't show bucket schema info on OSS bucket meta cards
influxdata/ui pull request #2524
Opened 2021-08-31 21:22 UTC by wbaker85

Closes #2520

Prevents bucket schema info from being shown on OSS, which does not have the concept of bucket schema.

2021-08-31 21:36 UTC, hoorayimhelping approved these changes

2021-08-31 22:11 UTC, wbaker85 commented
Guess this broke the unit tests so I'll need to figure out how to resolve that.

2021-08-31 22:20 UTC, wbaker85 commented
> Guess this broke the unit tests so I'll need to figure out how to resolve that.

should be fixed now

2021-09-01 20:04 UTC, jrenee42 requested changes

2021-09-01 20:04 UTC, jrenee42 commented on src/buckets/components/BucketCardMeta.tsx
> +    ? [schemaBlock, persistentBucketMeta]
please reverse the order!  (to keep the current order of the meta data, then the schema block

2021-09-01 20:24 UTC, jrenee42 approved these changes

2021-09-01 21:13 UTC, merged