chore: PAYG banner
influxdata/ui pull request #2760
Opened 2021-10-01 15:48 UTC by ShmuelLotman

Closes https://app.zenhub.com/workspaces/cloud-growth-5ff4b2ef8980820015495697/issues/influxdata/cloud-growth/155

Adds that little banner guy right up in the top right

2021-10-01 15:51 UTC, asalem1 reviewed
Do we have events in place to capture the click rate of the form so that we can compare the impact this has?

2021-10-01 15:51 UTC, asalem1 commented on src/checkout/CheckoutForm.scss
> +  width: 300px;
can we not do this with relative positioning?

2021-10-01 15:51 UTC, asalem1 commented on src/checkout/CheckoutForm.tsx
> +                <strong className="checkout-banner--credit">$250</strong>
Is this number an actual thing?

2021-10-01 15:53 UTC, ShmuelLotman commented on src/checkout/CheckoutForm.tsx
> +                <strong className="checkout-banner--credit">$250</strong>
YYes

2021-10-01 16:17 UTC, drdelambre requested changes
The css here is too specific with the positioning layout and won't stay consistent as screen sizes change.

2021-10-04 16:51 UTC, asalem1 approved these changes
"much gooder"

2021-10-04 18:48 UTC, drdelambre approved these changes
this is great. it decouples the parent from the child's designs so they can be altered independently

2021-10-04 18:49 UTC, merged