feat(wip): Billing Page
influxdata/ui pull request #342
Opened 2020-11-19 00:09 UTC by 121watts

2020-12-01 22:54 UTC, randycoulman requested changes
LGTM, but there's some copy-pasta in the endpoint descriptions to clean up.

For getting the user's e-mail, should we have a more generic return type for the `/billing/account` endpoint that includes the email in addition to the few account fields we need?

2020-12-01 22:54 UTC, randycoulman commented on src/client/unity.yml
> +          description: billing contact updated
Looks like some copy-pasta in this `put` definition; several references to billing contact and/or PaymentMethods, but this is about notification settings.

2020-12-01 22:54 UTC, randycoulman commented on src/client/unity.yml
> +          description: A Credit Card parameter object
copy-pasta?

2020-12-01 22:54 UTC, randycoulman commented on src/client/unity.yml
> +        - PaymentMethods
copy-pasta?

2020-12-01 22:54 UTC, randycoulman commented on src/client/unity.yml
> +        description: Invite to be sent
copy-pasta?

2020-12-01 23:04 UTC, drdelambre approved these changes

2020-12-01 23:49 UTC, 121watts commented
@randycoulman i fixed the copy pasta stuff and added email to the `Account` struct.

2020-12-02 00:06 UTC, randycoulman approved these changes

2020-12-02 00:16 UTC, Palakp41 approved these changes
👍

2020-12-02 16:30 UTC, merged