chore: remove export to client lib menu item for markdown
influxdata/ui pull request #3813
Opened 2022-02-09 16:55 UTC by subirjolly

Closes #3773

2022-02-09 16:58 UTC, drdelambre requested changes
mixing responsibilities

2022-02-09 17:44 UTC, subirjolly commented on src/flows/components/Sidebar.tsx
> +            const types = new Set(['markdown'])
As I mentioned to you over the chat, I started off with checking if `family` match would fit in this situation as that's generic. The issue with that is that `Markdown` belongs to `passThrough` family which some other panels do too. We don't want this menu to be disabled for other panels. As I mentioned, I am open to suggestions.

Is it appropriate to add a family or a family like attribute?

2022-02-09 17:50 UTC, subirjolly commented on src/flows/components/Sidebar.tsx
> +            const types = new Set(['markdown'])
possibly another solution can be to register optional `actions`?

2022-02-10 19:27 UTC, drdelambre approved these changes

2022-02-10 19:44 UTC, merged