feat(ecommerce): Removing delete account operator overlay
influxdata/ui pull request #3816
Opened 2022-02-09 18:42 UTC by djcarpe

Removes the `Delete Account` feature from the Account operator page. 

### Before
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/59489977/153268245-e5063e4e-7cb0-4b45-9e14-4e598197912a.png">

### After
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/59489977/153268113-a90b9886-e919-4343-9fb9-b8487e956a64.png">

2022-02-09 19:01 UTC, ChitlangeSahas approved these changes
Looks good to me! I think we should link the issue that this PR is trying to address, in the description.

2022-02-09 19:49 UTC, randycoulman requested changes
I believe that removing this button is gated on us having turned on the `freeAccountCancellation` feature flag everywhere first.

Given that, I think we either need to conditionally remove this button based on the feature flag value for now and actually delete the code later, or we need to hold off on merging this PR until we've completely turned on `freeAccountCancellation` and removed all code based on that feature flag.

2022-02-09 21:29 UTC, djcarpe commented
Good catch. Rather than letting this sit until we're ready I took your advice and feature flagged it so we can still test in staging.

2022-02-09 22:04 UTC, randycoulman reviewed
I'll let a UI team member give final approval, but one comment below.

2022-02-09 22:04 UTC, randycoulman commented on src/operator/account/AccountViewHeader.tsx
> +  const hideDeleteAccountButton = !isFlagEnabled('freeAccountCancellation')
This feels backwards to me if I'm reading this right (and with the logic below). Should this be named `showDeleteAccountButton` instead?

2022-03-07 19:01 UTC, randycoulman reviewed
This seems OK, but given that we're not sure we're moving forward with free account cancellation, it may not be worth merging at this time because we'll just have to remove it again later if we ultimately decide not to move forward.

Maybe let's wait until we finish scoping out what we're doing with cancellation before we merge this.

2022-05-25 14:54 UTC, djcarpe commented
This work is out dated.

2022-05-25 14:54 UTC, closed without merging