fix(3928): remove exportTask validation via hitting the queryEndpoint. Use heuristic instead.
influxdata/ui pull request #3994
Opened 2022-03-02 22:57 UTC by wiedld

Closes #3928 

Note: I cannot run remocal right now. So creating as a draft...in case anyone else wants to check it?

2022-03-03 00:53 UTC, drdelambre commented on src/flows/pipes/Notification/ExportTask.tsx
> +      heuristicValidityCheck(queryText)
Please remove. We can wait for the LSP updates if this is all we are testing

2022-03-04 17:10 UTC, drdelambre requested changes
we have a long history of generating issues that block production by doing this exact type of sting validation of queries within our interfaces. please remove.

2022-03-04 21:23 UTC, drdelambre commented on src/flows/pipes/Notification/ExportTask.tsx
> +    t => !!t.type && !!t.field && (t.value == 0 || !!t.value)
these aren't the rules for thresholds or threshold input

2022-03-04 22:18 UTC, wiedld commented
Compromised reached. Boatie gets only the code changes he wants (per https://github.com/influxdata/ui/pull/4018), and I wrote up a ticket addressing the larger problem we have with this feature (https://github.com/influxdata/ui/issues/4020).

2022-03-04 22:18 UTC, closed without merging