chore: upgrade clockface dependency to 2.4.0
influxdata/ui pull request #442
Opened 2020-12-16 20:57 UTC by alexpaxton

Introduces the ability to close an overlay via the escape key

- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass

2020-12-16 21:37 UTC, Asalem1 approved these changes

2020-12-16 23:23 UTC, Asalem1 commented
@alexpaxton I emailed you about what to do about the failures. My slack is struggling. Basically when @joelfried's fix makes it into the monitor-ci repo, you're gonna need to rerun the failing tests and it should be 👌🏽

2020-12-17 16:32 UTC, ShmuelLotman approved these changes

2020-12-18 19:45 UTC, ShmuelLotman requested changes
Not ready to merge yet.

2020-12-29 17:29 UTC, drdelambre commented
@ShmuelLotman did you get your changes pushed out to clockface to unblock this?

2020-12-29 17:31 UTC, ShmuelLotman commented
@drdelambre This needs to be changed to upgrade to 2.4.1. i have a separate PR in which that change happens as part of the overlay changes coming up, so i think we can scrap this one potentially and just wait to merge in the other one until everyone is back and we can get more eyes on the changes.

2021-02-05 21:03 UTC, closed without merging