refactor: turned it into a functional component
influxdata/ui pull request #455
Opened 2020-12-19 00:00 UTC by zoesteinkamp

Closes #349 

Describe your proposed changes here.
Changes to a functional component 

- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass

2020-12-19 13:08 UTC, Asalem1 approved these changes

2020-12-19 13:09 UTC, Asalem1 requested changes

2020-12-19 13:09 UTC, Asalem1 commented on src/authorizations/containers/TokensIndex.tsx
> -import {ErrorHandling} from 'src/shared/decorators/errors'
We should still want to integrate errorhandling here

2021-01-07 19:19 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 36 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | 22 | :red_circle:

2021-01-13 18:23 UTC, closed without merging