test: turn off TypeScript warnOnly
influxdata/ui pull request #541
Opened 2021-01-21 23:55 UTC by hoorayimhelping

TypeScript errors were temporarily turned to warnings. After reversing this back, some of the new billing tests have failed. This goes through and fixes the errors in those tests.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

2021-01-22 12:50 UTC, Asalem1 submitted a review, later dismissed
That's really strange that the tests are passing after removing the mock data. Basically the intention of those reducer tests was to ensure that specific property types were being set correctly without actually checking each property (besides the status). It stands to reason that the tests still pass since technically they're still equal to the input object, but I guess we should update the tests to check specific property types

2021-01-22 13:57 UTC, Asalem1 requested changes

2021-01-22 13:57 UTC, Asalem1 commented on src/billing/reducers/mockBillingData.ts
> -  region: 'eu-central',
Rather than removing the mock data from the mocks, we should update the test to check for these property types

2021-01-22 13:57 UTC, Asalem1 commented on src/usage/reducers/mockUsageData.ts
> -  time: '1/20/2021, 3:15:00 PM',
Same as the previous comment

2021-01-22 13:57 UTC, Asalem1 commented on src/usage/reducers/mockUsageData.ts
> -,,0,limited_write,2021-01-13T22:05:00Z,0`,
Same as the previous comment

2021-01-22 18:38 UTC, hoorayimhelping commented
>we should update the test to check for these property types

@Asalem1 Agreed. I was actually hoping you could help me with that. I tried to add some checks, but I was a bit lost between the tests and the TypeScript between unity and billing and couldn't get it to work. Would you mind taking a look at those tests when you have a minute?

2021-01-22 18:44 UTC, Asalem1 commented
> > we should update the test to check for these property types
> 
> @Asalem1 Agreed. I was actually hoping you could help me with that. I tried to add some checks, but I was a bit lost between the tests and the TypeScript between unity and billing and couldn't get it to work. Would you mind taking a look at those tests when you have a minute?

Definitely. Let me update the tests on master and push that up. i'll keep you posted on the progress

2021-01-22 18:48 UTC, hoorayimhelping commented
@Asalem1 if it helps, these errors should show up in the console when you run `yarn test`, they'll just be `WARN` level.

2021-01-26 01:04 UTC, hoorayimhelping commented on jestSetup.ts
> +jest.mock('src/shared/utils/errors')
fixes that one error about annotations on the flux response not existing

2021-01-26 01:05 UTC, hoorayimhelping commented on src/templates/components/CommunityTemplateInstallOverlay.test.tsx
no longer necessary since this call is being made in jestSetup

2021-01-26 01:19 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 52 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

2021-01-26 17:42 UTC, zoesteinkamp approved these changes
yay no more typescript warnonly

2021-01-26 17:45 UTC, merged