fix(schemaComposition): remove editor styles when sync is disabled
influxdata/ui pull request #5699
Opened 2022-09-08 15:20 UTC by appletreeisyellow

This PR fixes a bug listed in #5573. When the sync is disabled, the icon and highlight shouldn't be shown.

This fix is behind the feature flag `schemaComposition`

## Before

https://user-images.githubusercontent.com/14298407/189156754-e3f130ec-98c8-48f4-bfa9-f87a5a315746.mov

## After

https://user-images.githubusercontent.com/14298407/189156702-5d1327fb-6976-468e-8da6-992f541b8c93.mov

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
~~- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)~~
- [x] Feature flagged, if applicable

2022-09-08 16:40 UTC, wiedld commented on src/languageSupport/languages/flux/lsp/connection.ts
> +    const removeAllStyles = schema.composition.diverged
I think it should technically remove all styles when either: (1) there is no compositionBlock in the editor, or (2) it's diverged.

`!compositionBlock || schema.composition.diverged`

2022-09-08 16:40 UTC, wiedld requested changes

2022-09-08 16:40 UTC, wiedld commented on src/languageSupport/languages/flux/lsp/connection.ts
> +    const removeAllStyles = schema.composition.diverged
I think it should technically remove all styles when either: (1) there is no compositionBlock in the editor, or (2) it's diverged.

`!compositionBlock || schema.composition.diverged`

2022-09-08 16:57 UTC, appletreeisyellow commented on src/languageSupport/languages/flux/lsp/connection.ts
> +      clickableInvisibleDiv.style.display = 'block'
It's to make sure the sync icon and the highlight show up when a user clear the old Script and create a new Script

2022-09-08 21:55 UTC, wiedld approved these changes
LGTM!

2022-09-09 18:37 UTC, rockstar approved these changes

2022-09-09 18:38 UTC, merged