feat: Geo Map Type Customization Options
influxdata/ui pull request #575
Opened 2021-01-29 18:23 UTC by ShmuelLotman

Closes #9577

This PR introduces the initial implementation for the geo map type customization options. While the ticket listed more options than are available here, this is because certain types and options were more difficult to navigate than initially anticipated and thus have been moved to future tickets that will follow this initial work
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

2021-01-29 18:41 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 47 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

2021-01-29 20:22 UTC, hoorayimhelping requested changes
This is good overall, but there are a lot of little things that aren't very conventional within our codebase, and some things that should flat-out be changed.

I want you to replace all the default exports in new files in this diff with named exports:
https://basarat.gitbook.io/typescript/main-1/defaultisbad

2021-01-29 20:22 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +  const handleLatLongSelect = (latLonVal: number, type: string = 'lat') => {
not a huge fan of this type of function design. we have to pass in a value that represents either a latitude or a longitude depending on the second argument that sometimes gets passed in.

much clearer illustration of intent (and future use) to do something like this:

```ts
handleSelectLatitude(latitude: number) =>
  dispatch(setLatitude(latitude))

handleSelectLongitude(longitude: number) =>
  dispatch(SetLongitude(longitude))
```

then when it's called, you can just call 
```ts
  onChange={event => selectLatitude(parseFloat(event.target.value))}
```

this way, in the future, if there are some fancy business rules around how we select latitude, like say we have to apply a projection to it, we can easily do that without changing any code that consumes this function.

2021-01-29 20:22 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +  const handleSetPanZoom = () => {
```suggestion
  const handleTogglePanZoom = () => {
```
the function doesn't set anything, it just toggles a state

2021-01-29 20:22 UTC, hoorayimhelping commented on src/timeMachine/reducers/index.ts
> +    }
let's pull this out into a new file. it'll be easier to set up defaults and follow it that way

2021-01-29 20:22 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +        {displayCustomOptions(props.layers[0].type)}
same bit here about assumptions that layers is an array with an object with type

2021-01-29 20:22 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.test.tsx
> +  })
so i'm not sure if an integration test is the best course of action to test redux actions. the problem here is that we're deeply testing implementation, but not much behavior. we're basically saying "when this click happens, this function is called" which is a bit of antipattern. we want to assert something more along the lines of, "when a user clicks this button, the system's new state looks like this"

the difference is the case that tests behavior says "this is what i expect to happen" and the case that tests implementation says "this is what i expect you to do". tests of implementation have their place, but i don't think this is it. i think testing the reducer logic in a unit test will probably be more valuable. we can talk more about this in person though

2021-02-01 19:42 UTC, hoorayimhelping reviewed
some more suggestions

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/reducers/index.ts
> +      switch (state.view.properties.type) {
code style tip: no need to get fancy here, just use a normal early return guard statement:

```js
if (state?.view?.properties?.type === 'geo') {
  return setViewProperties(state, {zoom})
}

return state
}
```

**BUT** is this even necessary? Won't at this point, the `type` always be geo?

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/utils/geoMapTypeDefaults.ts
> +}
i love where your head is at here with creating these structures. let's keep them close to the redux store that uses them.

a hint that they should stay there is that the only two pieces of code that use these structures are the redux store and the code that tests the redux store.

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +enum LatMinMax {
```suggestion
enum LattitudeSliderRange {
```
thoughts?

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/CustomHeatmapOptions.tsx
> +    <Form.Element label="Radius" testID="heatmapradiusslider">
`geo-heatmap-radius-slider`

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +      <SelectGroup className="mapTypeOptions" testID="maptypeselect">
remove this `testID` if it's not being used

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +            testID="geo-latitude"
suggestion: a little more helpful when reading code outside here:
`geo-latitude-slider`

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +            testID="geo-longitude"
`geo-longitude-slider`

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +            testID="geo-zoom"
`geo-zoom-slider`

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/CustomHeatmapOptions.tsx
> +enum HeatMapRadiusMinMax {
```suggestion
enum HeatMapRadiusRange {
```

thoughts on `range` vs `minmax` ?

2021-02-01 19:42 UTC, hoorayimhelping commented on src/timeMachine/components/view_options/GeoOptions.tsx
> +      return null
```suggestion
    default: {
      return null
    }
```

2021-02-02 23:08 UTC, hoorayimhelping approved these changes

2021-02-03 00:03 UTC, merged