fix(5912): query with updated/latest time range
influxdata/ui pull request #5914
Opened 2022-09-27 20:40 UTC by wiedld

Closes #5912 

Fixing a bug I accidentally introduced yesterday (while fixing an unrelated bug).

Daterange updates is now being included in the extern payload:

https://user-images.githubusercontent.com/10232835/192630723-b5ac6587-6209-4d6e-8239-21a13eb91089.mov

## Checklist
- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] ~Feature flagged, if applicable~ N/A.

2022-09-27 20:42 UTC, appletreeisyellow submitted a review, later dismissed

2022-09-27 20:51 UTC, rockstar requested changes
For such a showstopper-like issue, I'd like to see a test that we don't regress here again.

2022-09-27 23:22 UTC, wiedld commented on cypress/e2e/shared/fluxQueryBuilder.test.ts
> +  const selectSchema = () => {
existing helper method. moved to outer scope.

2022-09-27 23:22 UTC, wiedld commented on cypress/e2e/shared/fluxQueryBuilder.test.ts
> +  const confirmSchemaComposition = () => {
existing helper method. moved to outer scope.

2022-09-28 00:22 UTC, rockstar approved these changes

2022-09-28 01:54 UTC, merged