docs(client_libs): update Node.js wizard to use new v3 client
influxdata/ui pull request #6762
Opened 2023-07-13 15:14 UTC by bednar

1. Changed `Node.js` wizard to use new https://github.com/bonitoo-io/influxdb3-js for `ioxOnboarding`

### Checklist

Authors and Reviewer(s), please verify the following:

- [ ] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [ ] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [ ] Documentation updated or issue created (provide link to issue/PR)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] Feature flagged, if applicable

2023-07-17 20:55 UTC, mavarius requested changes
Just a few changes:

1. These instructions are currently using the old example which writes 5 points in a loop. Please update it to use the new, more useful "insect census" example. This can be found in the other new guides like for Go, Python.

2. In the Client Libraries section of the Load Data page, update the card with the `write | query` tag.

![image](https://github.com/influxdata/ui/assets/11937365/983f7c88-7ae3-48d6-8edb-81e99c048e1c)

2023-07-18 04:40 UTC, mavarius requested changes

2023-07-18 04:40 UTC, mavarius commented on src/homepageExperience/components/steps/nodejs/ExecuteQuerySql.tsx
> +        Let's use that SQL query in our <code>Node.js</code> code to show us the
```suggestion
        Let's use that SQL query in our <code  className="homepage-wizard--code-highlight">Node.js</code> code to show us the
```

2023-07-18 04:40 UTC, mavarius commented on src/homepageExperience/components/steps/nodejs/ExecuteQuerySql.tsx
> +        Add the following code to the <code>main</code> function:
```suggestion
        Add the following code to the <code  className="homepage-wizard--code-highlight">main</code> function:
```

2023-07-18 04:40 UTC, mavarius commented on src/homepageExperience/components/steps/nodejs/WriteDataSql.tsx
> +        Add the following code to the <code>main</code> function:
```suggestion
        Add the following code to the <code  className="homepage-wizard--code-highlight">main</code> function:
```

2023-07-21 05:39 UTC, bednar commented on src/homepageExperience/components/steps/nodejs/WriteDataSql.tsx
The example is changed to "insect census".

2023-07-21 05:39 UTC, bednar commented on src/homepageExperience/components/steps/nodejs/ExecuteQuerySql.tsx
The example is changed to "insect census".

2023-07-26 22:38 UTC, mavarius approved these changes
Good to go!

2023-07-26 23:10 UTC, merged

2023-07-27 09:19 UTC, bednar commented
@mavarius thanks for your review