Delete annotations
influxdata/ui pull request #721
Opened 2021-02-18 05:56 UTC by zoesteinkamp

Closes #374 

- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass

2021-02-18 19:31 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 23 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 89 | :green_circle:
pwa | 22 | :red_circle:

2021-02-18 19:33 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 25 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 89 | :green_circle:
pwa | 22 | :red_circle:

2021-02-18 22:44 UTC, hoorayimhelping requested changes
great work, a couple of changes

2021-02-18 23:09 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 42 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

2021-02-19 23:30 UTC, zoesteinkamp commented on src/annotations/actions/thunks.ts
> +    dispatch(notify(deleteAnnotationSuccess()))
added!

2021-03-10 22:00 UTC, closed without merging