refactor: use single stat from giraffe in singleStatWithLine
influxdata/ui pull request #837
Opened 2021-03-13 17:31 UTC by ChitlangeSahas

We want to use the giraffe's component instead of the UI's old code.

_Note: Currently using a variable to mock a feature flag, will add the feature flag logic once the feature flag is ready in the configCat._

Giraffe's single stat component renders in UI:

<img width="1440" alt="Screen Shot 2021-03-13 at 10 30 47 AM" src="https://user-images.githubusercontent.com/18511823/111038623-41d38f80-83e7-11eb-9f80-1848218de813.png">

- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass

2021-03-13 17:44 UTC, hercules-influx commented
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 42 | :red_circle:
accessibility | 87 | :green_circle:
best-practices | 87 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:

2021-03-17 22:34 UTC, TCL735 requested changes

2021-03-17 22:34 UTC, TCL735 commented on src/visualization/types/SingleStatWithLine/view.tsx
> +  const latestValues = getLatestValues(result.table)
Similar to my comments on https://github.com/influxdata/ui/pull/830
`getLatestValues` should exported in Giraffe. `formatStatValue` should also be exported. Release a new version of Giraffe and then consume it here.

2021-03-23 21:50 UTC, TCL735 approved these changes

2021-03-23 21:56 UTC, merged